apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3040  # Port your Node.js app listens on
  type: LoadBalancer  # Expose the service with LoadBalancer
